server:
  port: 9000

spring:
  application:
    name: spring-cloud-study-zuul
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:5000/eureka/
 
zuul:
  routes:
    consummer:
      service-id: spring-cloud-study-consummer
      path: /consummer/**
  ignored-services:
  - '*'  
    