server:
  port: 3000

spring:
  application:
    name: spring-cloud-study-provider
    
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:5000/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
        - hystrix.stream 
     
